[package]
name = "game"
version = "0.1.0"
edition = "2021"

[dependencies]
engine = { path = "../engine" }
winit = "0.29"
wgpu = "0.20"
pollster = "0.3"
env_logger = "0.11"
log = "0.4"
bytemuck = { version = "1.16", features = ["derive"] }
gltf = "1.4"
tobj = "4"
stl_io = "0.4"
rayon = "1.10"
